# Generated by Django 6.0.2 on 2026-02-17 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_alter_review_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='gender_preference',
            field=models.CharField(choices=[('Mixed', 'Mixed (Gents & Ladies)'), ('Gents', 'Gents Only'), ('Ladies', 'Ladies Only')], default='Mixed', max_length=10),
        ),
    ]
