# Generated by Django 6.0.2 on 2026-02-17 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_property_gender_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='program',
            field=models.CharField(blank=True, help_text='e.g. Computer Science', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='year_of_study',
            field=models.CharField(blank=True, help_text='e.g. Year 2', max_length=20),
        ),
    ]
