# Generated by Django 6.0.2 on 2026-02-17 13:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_profile_bio_profile_company_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='favorite_properties', to=settings.AUTH_USER_MODEL),
        ),
    ]
