# Generated by Django 6.0.2 on 2026-02-18 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_room_booking_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyimage',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_images', to='listings.room'),
        ),
    ]
