# Generated by Django 6.0.2 on 2026-02-19 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_propertyimage_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='curfew',
            field=models.CharField(blank=True, help_text='e.g. 10:00 PM (Leave blank if none)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='deposit_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Enter 0 if no deposit', max_digits=10),
        ),
        migrations.AddField(
            model_name='property',
            name='has_borehole',
            field=models.BooleanField(default=False, verbose_name='Borehole / Backup Water'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_solar',
            field=models.BooleanField(default=False, verbose_name='Solar Power'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_wifi',
            field=models.BooleanField(default=False, verbose_name='Wi-Fi'),
        ),
        migrations.AddField(
            model_name='property',
            name='visitors_allowed',
            field=models.BooleanField(default=True, verbose_name='Visitors Allowed'),
        ),
    ]
